# The Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Paris

title: Docker Cloudflare Tunnel Sync
tagline: Traefik-like labels for Cloudflare Tunnel
description: >-
  Expose Docker services through Cloudflare Tunnel using Docker labels,
  with optional DNS and Access sync.

url: "https://docker-cloudflare-tunnel-sync.darkdragon14.dev"
baseurl: ""

github:
  username: darkdragon14

social:
  name: Docker Cloudflare Tunnel Sync
  links:
    - https://github.com/darkdragon14/docker-cloudflare-tunnel-sync

theme_mode:
cdn:
avatar: /assets/logo.png
social_preview_image: /assets/logo.png
toc: true

comments:
  provider:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

kramdown:
  footnote_backlink: "back"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
      toc: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - .bundle
  - .jekyll-cache
  - _site

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
